# Generated by Django 5.1.3 on 2024-12-07 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_users_email_alter_users_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='password_hash',
            new_name='password',
        ),
    ]
